import { defineLocalizedCopy, localizedCopyFor } from '../../i18n/localizedCopy'

const ptBR = {
  button: 'Comunidade',
  title: 'Mods da comunidade',
  subtitle: 'Receitas de mods enviadas pela comunidade e revisadas pela equipe do Moddin.',
  close: 'Fechar',
  refreshEvery: 'Buscar novidades',
  lastUpdated: 'Atualizado em {timestamp}',
  never: 'nunca',
  refreshNow: 'Atualizar agora',
  catalogVerified: 'Catálogo oficial verificado',
  catalogNotVerified: 'Não foi possível confirmar que o catálogo é oficial',
  keyFingerprint: 'Chave de segurança: {fingerprint}',
  empty: 'Nenhum mod da comunidade por aqui ainda. Clique em "Atualizar agora" para buscar a lista mais recente.',
  loading: 'Buscando a lista da comunidade…',
  signed: 'Verificado',
  unsigned: 'Não verificado',
  acceptUnsigned: 'Entendo que este mod não foi verificado pela equipe do Moddin e quero instalar mesmo assim.',
  install: 'Instalar',
  installing: 'Instalando…',
  installed: '{name} foi instalado. Você pode desfazer no Histórico.',
  installFailed: 'Não foi possível instalar: {error}',
  notInCatalog: 'Este mod não está mais na lista da comunidade. Atualize e tente de novo.',
  needsConsent: 'Este mod não foi verificado. Marque a caixa de confirmação para instalar.',
  builtInHeading: 'Receitas já disponíveis no seu Moddin ({count})',
  originBuiltIn: 'Incluída no app',
  originLocal: 'Sua pasta local',
  originCommunity: 'Comunidade',
  ttlManual: 'Só quando eu pedir',
  ttlHours: 'A cada {count} h',
  ttlDaily: 'Uma vez por dia',
  ttlDays: 'A cada {count} dias',
  errorSigTitle: 'A assinatura do catálogo não bate.',
  errorSigWhy: 'O catálogo foi assinado por outra chave ou foi modificado depois de assinado. Atualize o Moddin (ou peça ao mantenedor para republicar o catálogo).',
  errorNetworkTitle: 'Não consegui falar com o servidor do catálogo.',
  errorNetworkWhy: 'Verifique sua conexão com a internet e tente de novo. O servidor pode estar fora do ar por alguns minutos.',
  errorMissingTitle: 'O catálogo não foi encontrado no servidor.',
  errorMissingWhy: 'O repositório da comunidade pode ter sido movido ou ainda não publicou um catálogo. Veja o status em github.com/petonexus/moddin-community-capabilities.',
  errorGenericTitle: 'Não consegui buscar o catálogo agora.',
  errorGenericWhy: 'Algo deu errado. Tente de novo em alguns segundos. Se persistir, abra uma issue em github.com/petonexus/moddin-desktop.',
  errorRawToggle: 'Ver detalhe técnico',
} as const

const communityMessages = defineLocalizedCopy(
  ptBR,
  {
    button: 'Community',
    title: 'Community mods',
    subtitle: 'Mod recipes shared by the community and reviewed by the Moddin team.',
    close: 'Close',
    refreshEvery: 'Check for new mods',
    lastUpdated: 'Updated {timestamp}',
    never: 'never',
    refreshNow: 'Refresh now',
    catalogVerified: 'Official catalog verified',
    catalogNotVerified: 'Could not confirm this is the official catalog',
    keyFingerprint: 'Security key: {fingerprint}',
    empty: 'No community mods yet. Click "Refresh now" to fetch the latest list.',
    loading: 'Fetching the community list…',
    signed: 'Verified',
    unsigned: 'Not verified',
    acceptUnsigned: 'I understand this mod was not verified by the Moddin team and I want to install it anyway.',
    install: 'Install',
    installing: 'Installing…',
    installed: '{name} was installed. You can undo it from History.',
    installFailed: 'Could not install: {error}',
    notInCatalog: 'This mod is no longer in the community list. Refresh and try again.',
    needsConsent: 'This mod is not verified. Tick the confirmation box to install it.',
    builtInHeading: 'Recipes already in your Moddin ({count})',
    originBuiltIn: 'Built in',
    originLocal: 'Your local folder',
    originCommunity: 'Community',
    ttlManual: 'Only when I ask',
    ttlHours: 'Every {count} h',
    ttlDaily: 'Once a day',
    ttlDays: 'Every {count} days',
    errorSigTitle: 'The catalog signature does not match.',
    errorSigWhy: 'The catalog was signed by a different key or was modified after signing. Update Moddin (or ask the maintainer to re-publish the catalog).',
    errorNetworkTitle: 'Could not reach the catalog server.',
    errorNetworkWhy: 'Check your internet connection and try again. The server may be down for a few minutes.',
    errorMissingTitle: 'The catalog was not found on the server.',
    errorMissingWhy: 'The community repo may have moved, or has not published a catalog yet. Check status at github.com/petonexus/moddin-community-capabilities.',
    errorGenericTitle: 'Could not fetch the catalog right now.',
    errorGenericWhy: 'Something went wrong. Try again in a few seconds. If it persists, open an issue at github.com/petonexus/moddin-desktop.',
    errorRawToggle: 'Show technical detail',
  },
  {
    button: 'Comunidad',
    title: 'Mods de la comunidad',
    subtitle: 'Recetas de mods compartidas por la comunidad y revisadas por el equipo de Moddin.',
    close: 'Cerrar',
    refreshEvery: 'Buscar novedades',
    lastUpdated: 'Actualizado el {timestamp}',
    never: 'nunca',
    refreshNow: 'Actualizar ahora',
    catalogVerified: 'Catálogo oficial verificado',
    catalogNotVerified: 'No se pudo confirmar que el catálogo sea oficial',
    keyFingerprint: 'Clave de seguridad: {fingerprint}',
    empty: 'Todavía no hay mods de la comunidad. Pulsa "Actualizar ahora" para buscar la lista más reciente.',
    loading: 'Buscando la lista de la comunidad…',
    signed: 'Verificado',
    unsigned: 'Sin verificar',
    acceptUnsigned: 'Entiendo que este mod no fue verificado por el equipo de Moddin y quiero instalarlo igualmente.',
    install: 'Instalar',
    installing: 'Instalando…',
    installed: '{name} se instaló. Puedes deshacerlo desde el Historial.',
    installFailed: 'No se pudo instalar: {error}',
    notInCatalog: 'Este mod ya no está en la lista de la comunidad. Actualiza e inténtalo de nuevo.',
    needsConsent: 'Este mod no está verificado. Marca la casilla de confirmación para instalarlo.',
    builtInHeading: 'Recetas ya disponibles en tu Moddin ({count})',
    originBuiltIn: 'Incluida en la app',
    originLocal: 'Tu carpeta local',
    originCommunity: 'Comunidad',
    ttlManual: 'Solo cuando lo pida',
    ttlHours: 'Cada {count} h',
    ttlDaily: 'Una vez al día',
    ttlDays: 'Cada {count} días',
    errorSigTitle: 'La firma del catálogo no coincide.',
    errorSigWhy: 'El catálogo fue firmado con otra clave o se modificó después de firmar. Actualiza Moddin (o pide al mantenedor que vuelva a publicar el catálogo).',
    errorNetworkTitle: 'No pude contactar al servidor del catálogo.',
    errorNetworkWhy: 'Verifica tu conexión a internet e inténtalo otra vez. El servidor puede estar caído unos minutos.',
    errorMissingTitle: 'No se encontró el catálogo en el servidor.',
    errorMissingWhy: 'El repo de la comunidad puede haberse movido o aún no publicó un catálogo. Revisa el estado en github.com/petonexus/moddin-community-capabilities.',
    errorGenericTitle: 'No pude obtener el catálogo ahora mismo.',
    errorGenericWhy: 'Algo salió mal. Inténtalo otra vez en unos segundos. Si persiste, abre un issue en github.com/petonexus/moddin-desktop.',
    errorRawToggle: 'Ver detalle técnico',
  },
)

export function communityCopyForLocale(locale: string) {
  return localizedCopyFor(communityMessages, locale)
}

export function formatCopy(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match))
}
