import { defineLocalizedCopy, localizedCopyFor } from '../../i18n/localizedCopy'

const ptBR = {
  button: 'Atividades',
  title: 'Registro de atividades',
  subtitle: 'Tudo o que o Moddin fez, com detalhes para investigar problemas.',
  refresh: 'Atualizar',
  clear: 'Apagar registro',
  close: 'Fechar',
  search: 'Buscar no registro…',
  all: 'Todos',
  success: 'sucesso',
  error: 'erro',
  warning: 'aviso',
  info: 'info',
  empty: 'Nenhuma atividade registrada ainda.',
  details: 'Detalhes',
  transaction: 'Mudança',
  game: 'Jogo',
  confirmClear: 'Apagar todo o registro de atividades? Isso não desfaz nenhuma mudança nos seus jogos.',
  storage: 'Salvo em %LOCALAPPDATA%\\Moddin\\logs (até 5 MB).',
} as const

const activityMessages = defineLocalizedCopy(
  ptBR,
  {
    button: 'Activity',
    title: 'Activity log',
    subtitle: 'Everything Moddin did, with details for troubleshooting.',
    refresh: 'Refresh',
    clear: 'Clear log',
    close: 'Close',
    search: 'Search the log…',
    all: 'All',
    success: 'success',
    error: 'error',
    warning: 'warning',
    info: 'info',
    empty: 'No activity recorded yet.',
    details: 'Details',
    transaction: 'Change',
    game: 'Game',
    confirmClear: 'Clear the whole activity log? This does not undo any change to your games.',
    storage: 'Saved in %LOCALAPPDATA%\\Moddin\\logs (up to 5 MB).',
  },
  {
    button: 'Actividad',
    title: 'Registro de actividad',
    subtitle: 'Todo lo que hizo Moddin, con detalles para investigar problemas.',
    refresh: 'Actualizar',
    clear: 'Borrar registro',
    close: 'Cerrar',
    search: 'Buscar en el registro…',
    all: 'Todos',
    success: 'éxito',
    error: 'error',
    warning: 'aviso',
    info: 'info',
    empty: 'Aún no hay actividad registrada.',
    details: 'Detalles',
    transaction: 'Cambio',
    game: 'Juego',
    confirmClear: '¿Borrar todo el registro de actividad? Esto no deshace ningún cambio en tus juegos.',
    storage: 'Guardado en %LOCALAPPDATA%\\Moddin\\logs (hasta 5 MB).',
  },
)

export function activityCopyForLocale(locale: string) {
  return localizedCopyFor(activityMessages, locale)
}
