//! Community catalog fetcher.
//!
//! Downloads the curated capability list from
//! `petonexus/moddin-community-capabilities` on GitHub, verifies it
//! against the pinned maintainer public key, and caches the result
//! locally with a configurable TTL (default 24h).
//!
//! ## Threat model
//!
//! The bootstrap public key is compiled into the binary. The runner
//! REJECTS any catalog whose Ed25519 signature does not verify against
//! that key. If the maintainer rotates the key, a new Moddin Desktop
//! release carries the new key — release-time rotation is intentional
//! friction for the highest-trust asset.
//!
//! ## One signature, two jobs
//!
//! The capability list *and* the maintainers' kill switch both live in
//! the signed `catalog.json`, under the top-level `revoked` key. They
//! used to arrive separately — `revoked-ids.json` was fetched over its
//! own GET — and that was a second, **unauthenticated** trust channel:
//! whoever could intercept that one request could suppress a revocation
//! until the TTL expired, and the cache re-verification added for the
//! catalog could not help, because the list is trusted precisely when
//! it is stale. Inlining it under the same signature closes that, and
//! makes the two halves impossible to disagree about.
//!
//! ## Cache layout
//!
//! ```text
//! %LOCALAPPDATA%\Moddin\community-capabilities\
//!   catalog.json      ← cached payload, byte-for-byte as it was signed
//!   catalog.sig       ← the Ed25519 signature that covers those bytes
//!   catalog.meta.json ← { cachedAt, ttlSeconds, signatureVerified }
//!   pinned-public-key.bin ← Ed25519 raw 32 bytes
//! ```
//!
//! Builds from before the revocations moved may still have a
//! `revoked-ids.json` in that directory. Nothing reads it any more and
//! it is deliberately left on disk rather than deleted: it is the user's
//! file, and a stale copy of it is inert precisely because the
//! revocation list now comes from the signed bytes.
//!
//! `catalog.json` is never re-serialised on the way to disk: the
//! signature covers the exact bytes the maintainer signed, and a
//! re-formatted cache would stop verifying. Anything that reads a
//! cached `downloadUrl` therefore has to re-verify `catalog.json`
//! against `catalog.sig` with a key from [`TRUSTED_PUBLIC_KEYS_B64`]
//! first — the stored `signatureVerified` boolean is a cache file just
//! like the rest, and a writer of `%LOCALAPPDATA%` can set it to
//! `true` without a private key.
//!
//! ## TTL
//!
//! * 1h, 6h, 24h, 7d, or manual (refresh-only). Stored in
//!   `catalog.meta.json`.
//! * When the cache is fresh, no network calls happen.
//! * When expired, a single GET pulls both the catalog and the signature
//!   (the signature ships as a sibling file or, in the future, as a
//!   GitHub Release asset).

use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::{
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

const CATALOG_URL: &str =
    "https://raw.githubusercontent.com/petonexus/moddin-community-capabilities/main/catalog.json";
const CATALOG_SIG_URL: &str =
    "https://raw.githubusercontent.com/petonexus/moddin-community-capabilities/main/catalog.json.sig";

/// Hosts a community capability YAML (and its sibling `SIGNED-BY`) may
/// be fetched from. Same shape as the `download-file` allow-list in
/// [`crate::builtin_steps`]: a closed default, overridable only by an
/// explicit declaration from the caller. `raw.githubusercontent.com` is
/// here because every `downloadUrl` in the community catalog points at
/// it — dropping it would make the feature uninstallable rather than
/// safer.
const CAPABILITY_YAML_HOST_ALLOWLIST: &[&str] = &[
    "github.com",
    "objects.githubusercontent.com",
    "raw.githubusercontent.com",
];

const DEFAULT_TTL_SECONDS: u64 = 24 * 60 * 60;
const MIN_TTL_SECONDS: u64 = 60 * 60; // 1h floor
const MAX_TTL_SECONDS: u64 = 30 * 24 * 60 * 60; // 30d ceiling

/// Cache file names. `catalog.json` and `catalog.sig` are written as a
/// pair; reading one without the other is a cache miss, not a fallback.
const CATALOG_CACHE_FILE: &str = "catalog.json";
const CATALOG_SIG_CACHE_FILE: &str = "catalog.sig";
const CATALOG_META_FILE: &str = "catalog.meta.json";

/// Bootstrap public key compiled into the binary. Generated by
/// `cargo run --example gen_maintainer_key`. Matched against the
/// maintainer entry in
/// [`petonexus/moddin-community-capabilities` `public-keys.json`](https://github.com/petonexus/moddin-community-capabilities)
/// — the first 16 hex chars of SHA-256 over these 32 bytes are
/// `d489a3a0be894b19`. Rotating the maintainer key requires a new
/// Moddin Desktop release with the updated constant.
const BOOTSTRAP_PUBLIC_KEY_B64: &str = "JURnO8HhZDsJdoTFEeF4mq1pDgFnfXN0/OZgPuzJKfc=";

/// Every key this build is willing to trust, newest first.
///
/// This is the trust anchor. `pinned-public-key.bin` on disk is a
/// *cache* of which of these is active, not an independent source of
/// trust: anything that could write to `%LOCALAPPDATA%` could also
/// write a key of its own there, and the previous implementation
/// returned whatever 32 bytes it found without ever comparing it to
/// the compiled value. That is trust-on-first-use with no anchor, in a
/// product whose pitch is that it signs what it installs.
///
/// Rotation is therefore: add the new key to this list and ship a
/// build, which is the same cadence the keyring in the community repo
/// documents. Keeping the previous key for one release lets users who
/// have not updated yet finish a verification instead of seeing a hard
/// failure. A key that is compromised goes in `REVOKED_KEY_FINGERPRINTS`
/// below and never has to wait for a build to be neutralised in the
/// on-disk cache, because the cache is only ever accepted when it
/// matches a key that is neither absent from this list nor revoked.
const TRUSTED_PUBLIC_KEYS_B64: &[&str] = &[
    // @moddin-bot, active since the authorized 2026-10-02 rotation.
    BOOTSTRAP_PUBLIC_KEY_B64,
    // Previous anchor retained during this release's transition.
    "R2oSrMGh0d6pHIWFHZwvU+sA+wK1Uo/vaBq/L1WJ6GU=",
];

/// Fingerprints (first 16 hex of SHA-256, as shown in the UI) that
/// must never be trusted, even if they appear in [`TRUSTED_PUBLIC_KEYS_B64`].
const REVOKED_KEY_FINGERPRINTS: &[&str] = &[];

fn community_dir() -> Option<PathBuf> {
    std::env::var_os("LOCALAPPDATA")
        .map(PathBuf::from)
        .map(|dir| dir.join("Moddin").join("community-capabilities"))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunityCatalogEntry {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub display_name: String,
    #[serde(default)]
    pub category: String,
    #[serde(default)]
    pub status: String,
    #[serde(default)]
    pub homepage: Option<String>,
    #[serde(default)]
    pub download_url: Option<String>,
    /// Digest of the exact YAML bytes, covered by the catalog signature.
    #[serde(default)]
    pub yaml_sha256: Option<String>,
    #[serde(default)]
    pub config_schema: serde_json::Value,
    #[serde(default)]
    pub safety_notes: Vec<String>,
    #[serde(default)]
    pub signed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunityCatalog {
    pub version: u32,
    #[serde(default)]
    pub generated_at: String,
    #[serde(default)]
    pub generator: String,
    #[serde(default)]
    pub capabilities: Vec<CommunityCatalogEntry>,
    /// The maintainers' kill switch, carried inside the signed bytes.
    ///
    /// `regenerate_catalog.py` inlines `revoked-ids.json` here so one
    /// signature covers the capability list and the revocation list
    /// together. The result carries no `revocationsVerified` flag
    /// because there is nothing left to verify separately: this list is
    /// trustworthy exactly when [`CommunityFetchResult::signature_verified`]
    /// is, because it is the same signature over the same bytes.
    #[serde(default, deserialize_with = "deserialize_revocations")]
    pub revoked: Vec<RevokedEntry>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunityFetchResult {
    pub catalog: CommunityCatalog,
    pub cached: bool,
    pub cached_at: u64,
    pub ttl_seconds: u64,
    pub signature_verified: bool,
    pub bootstrap_public_key_fingerprint: String,
    pub last_error: Option<String>,
}

/// One entry of the catalogue's `revoked` list, inlined by
/// `regenerate_catalog.py` from `revoked-ids.json`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RevokedEntry {
    pub id: String,
    #[serde(default)]
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CacheMetadata {
    cached_at: u64,
    ttl_seconds: u64,
    signature_verified: bool,
    bootstrap_fingerprint: String,
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

/// Decode one base64 Ed25519 public key.
fn decode_public_key(encoded: &str) -> Result<VerifyingKey, String> {
    let bytes = BASE64
        .decode(encoded.trim())
        .map_err(|error| format!("public key is not valid base64: {error}"))?;
    if bytes.len() != 32 {
        return Err(format!(
            "Ed25519 public key must be 32 bytes, got {}",
            bytes.len()
        ));
    }
    let array: [u8; 32] = bytes
        .as_slice()
        .try_into()
        .map_err(|error: std::array::TryFromSliceError| error.to_string())?;
    VerifyingKey::from_bytes(&array).map_err(|error| format!("invalid Ed25519 key: {error}"))
}

/// Verify `payload` against **every** key in `keys`, not one key the
/// cache happens to point at.
///
/// This is the check that makes the on-disk cache safe to read. A
/// cached catalogue is only as trustworthy as the signature that covers
/// it, and the signature is only meaningful if the key it was checked
/// against comes from the compiled keyring rather than from the same
/// directory the attacker is writing to. Revoked fingerprints are
/// skipped by [`is_key_revoked`], so a compromised key stops working
/// without a release.
///
/// The key list is a parameter so a test can exercise the *accept* path
/// — the build ships no private key, so there is otherwise no way to
/// produce a catalogue the app is supposed to trust. Production callers
/// pass [`TRUSTED_PUBLIC_KEYS_B64`] and nothing else.
fn verify_with_keys(
    payload: &[u8],
    signature_b64: &str,
    keys: &[&str],
) -> Result<VerifyingKey, String> {
    let mut rejection: Option<String> = None;
    for encoded in keys {
        let key = match decode_public_key(encoded) {
            Ok(key) => key,
            Err(error) => {
                rejection.get_or_insert(format!("trust list entry {encoded} is unusable: {error}"));
                continue;
            }
        };
        if is_key_revoked(&key) {
            rejection.get_or_insert(format!("key {encoded} is revoked"));
            continue;
        }
        match verify_signature(payload, signature_b64, &key) {
            Ok(()) => return Ok(key),
            Err(error) => {
                rejection.get_or_insert(error);
            }
        }
    }
    Err(rejection.unwrap_or_else(|| "no trusted key is available".to_owned()))
}

/// Is this key one this build is willing to trust?
pub(crate) fn is_trusted(key: &VerifyingKey) -> bool {
    is_trusted_in(key, TRUSTED_PUBLIC_KEYS_B64)
}

fn is_trusted_in(key: &VerifyingKey, keys: &[&str]) -> bool {
    if is_key_revoked(key) {
        return false;
    }
    keys.iter()
        .filter_map(|encoded| decode_public_key(encoded).ok())
        .any(|trusted| trusted.to_bytes() == key.to_bytes())
}

/// A fingerprint that must never be trusted, even if a key list still
/// carries it.
fn is_key_revoked(key: &VerifyingKey) -> bool {
    REVOKED_KEY_FINGERPRINTS.contains(&fingerprint(key).as_str())
}

/// Resolve the key used to verify the community catalog.
///
/// The on-disk pin is accepted only when it matches a key from
/// [`TRUSTED_PUBLIC_KEYS_B64`]. A pin that does not match is discarded
/// and the anchor is used instead — so tampering with the cache
/// degrades to "no worse than a fresh install" rather than to
/// "attacker-chosen key". A corrupt or revoked pin is reported so the
/// user is not silently handed a different key than the one they
/// were shown a fingerprint for.
fn ensure_bootstrap_key_material(dir: &Path) -> Result<VerifyingKey, String> {
    let anchor = decode_public_key(BOOTSTRAP_PUBLIC_KEY_B64)?;

    let path = dir.join("pinned-public-key.bin");
    let mut pin_rejected: Option<String> = None;
    if let Ok(bytes) = std::fs::read(&path) {
        match <[u8; 32]>::try_from(bytes.as_slice()) {
            Ok(array) => match VerifyingKey::from_bytes(&array) {
                Ok(key) if is_trusted(&key) => return Ok(key),
                Ok(key) => {
                    pin_rejected = Some(format!(
                        "pinned key {} is not in this build's trust list",
                        fingerprint(&key)
                    ));
                }
                Err(_) => pin_rejected = Some("pinned key is not a valid Ed25519 point".to_owned()),
            },
            Err(_) => {
                pin_rejected = Some(format!("pinned key is {} bytes, expected 32", bytes.len()))
            }
        }
    }

    if let Some(reason) = pin_rejected {
        eprintln!("moddin: {reason}; falling back to the compiled trust anchor");
    }

    // Repair the cache so the mismatch is not re-reported on every call.
    let _ = pin_pinned_public_key(dir, &anchor);
    Ok(anchor)
}

fn fingerprint(key: &VerifyingKey) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(key.to_bytes());
    let digest = hasher.finalize();
    let hex = digest
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    hex.chars().take(16).collect()
}

/// The unverified read of the cached catalogue, kept for tests only.
///
/// Nothing in the app is allowed to call this: it is here so a test can
/// assert that a tampered cache *is* accepted by the plain read, which
/// is what makes the verified read's refusal meaningful rather than
/// vacuous.
#[cfg(test)]
fn read_cached_catalog(dir: &Path) -> Option<(CommunityCatalog, CacheMetadata)> {
    let raw = std::fs::read_to_string(dir.join(CATALOG_CACHE_FILE)).ok()?;
    let meta_raw = std::fs::read_to_string(dir.join(CATALOG_META_FILE)).ok()?;
    let catalog: CommunityCatalog = serde_json::from_str(&raw).ok()?;
    let meta: CacheMetadata = serde_json::from_str(&meta_raw).ok()?;
    Some((catalog, meta))
}

/// Read the cached catalogue **only** if its bytes still verify against
/// a key from the trust ring.
///
/// `read_cached_catalog` is the raw read; it is what the freshness check
/// needs when it only wants to look at the TTL. Anything that consumes a
/// value out of a cached entry — a `downloadUrl` above all — has to come
/// through here instead, because `catalog.meta.json`'s
/// `signatureVerified: true` is just another field in a file an attacker
/// with write access to `%LOCALAPPDATA%` can flip.
fn read_verified_cached_catalog(
    dir: &Path,
) -> Result<(CommunityCatalog, CacheMetadata, VerifyingKey), String> {
    read_verified_cached_catalog_with_keys(dir, TRUSTED_PUBLIC_KEYS_B64)
}

fn read_verified_cached_catalog_with_keys(
    dir: &Path,
    keys: &[&str],
) -> Result<(CommunityCatalog, CacheMetadata, VerifyingKey), String> {
    let bytes = std::fs::read(dir.join(CATALOG_CACHE_FILE))
        .map_err(|error| format!("cached catalog could not be read: {error}"))?;
    let signature = std::fs::read_to_string(dir.join(CATALOG_SIG_CACHE_FILE))
        .map_err(|error| format!("cached catalog signature is missing: {error}"))?;
    let key = verify_with_keys(&bytes, &signature, keys)?;
    let catalog: CommunityCatalog = serde_json::from_slice(&bytes)
        .map_err(|error| format!("cached catalog JSON is malformed: {error}"))?;
    let meta: CacheMetadata = serde_json::from_str(
        &std::fs::read_to_string(dir.join(CATALOG_META_FILE))
            .map_err(|error| format!("cached catalog metadata could not be read: {error}"))?,
    )
    .map_err(|error| format!("cached catalog metadata is malformed: {error}"))?;
    Ok((catalog, meta, key))
}

fn write_cache(
    dir: &Path,
    raw_catalog: &[u8],
    signature: &str,
    meta: &CacheMetadata,
) -> Result<(), String> {
    std::fs::create_dir_all(dir)
        .map_err(|error| format!("could not create community cache dir: {error}"))?;
    // `raw_catalog` is the exact byte string the maintainer signed, not
    // a re-serialisation of the parsed value: normalising it here would
    // change bytes the signature covers and the cache would stop
    // verifying the next time it is read.
    std::fs::write(dir.join(CATALOG_CACHE_FILE), raw_catalog)
        .map_err(|error| format!("could not write catalog.json: {error}"))?;
    std::fs::write(dir.join(CATALOG_SIG_CACHE_FILE), signature.trim())
        .map_err(|error| format!("could not write catalog.sig: {error}"))?;
    std::fs::write(
        dir.join(CATALOG_META_FILE),
        serde_json::to_vec_pretty(meta)
            .map_err(|error| format!("could not serialise metadata: {error}"))?,
    )
    .map_err(|error| format!("could not write catalog.meta.json: {error}"))?;
    Ok(())
}

/// Read the `revoked` field out of a signed catalogue.
///
/// An **absent** key (and an explicit `null`) is a statement by the
/// maintainer that nothing is revoked, and yields an empty list. That
/// is a deliberate reading, not a default: requiring the key would buy
/// no protection — an attacker able to strip it could equally rewrite
/// the whole catalogue, and then the signature check refuses every
/// install anyway — while bricking community installs against any
/// catalogue generated before the field existed.
///
/// Everything else is a broken file rather than a statement, and fails
/// closed. Strict on purpose: an entry without a usable `id` cannot be
/// matched against a capability, and dropping it on the floor is exactly
/// the kind of "bounded but wrong" reading this module avoids — a typo
/// in a revocation must not turn into a revoked mod that still installs.
fn parse_revocations(raw: Option<&serde_json::Value>) -> Result<Vec<RevokedEntry>, String> {
    let Some(raw) = raw else {
        return Ok(Vec::new());
    };
    let items = raw.as_array().ok_or_else(|| {
        format!(
            "catalog 'revoked' must be an array of {{id, reason}} entries, found {}",
            json_kind(raw)
        )
    })?;
    items.iter().map(parse_revoked_entry).collect()
}

fn parse_revoked_entry(value: &serde_json::Value) -> Result<RevokedEntry, String> {
    let entry = value.as_object().ok_or_else(|| {
        format!(
            "every catalog 'revoked' entry must be an object with an id, found {}",
            json_kind(value)
        )
    })?;

    // Trimmed on the way in: a stray space in the maintainer's file must
    // still revoke the capability, not quietly miss it. That errs toward
    // refusing more, which is the safe direction for a kill switch.
    let id = match entry.get("id") {
        Some(serde_json::Value::String(id)) if !id.trim().is_empty() => id.trim().to_owned(),
        Some(other) => {
            return Err(format!(
                "catalog 'revoked'[].id must be a non-empty string, found {}",
                json_kind(other)
            ))
        }
        None => {
            return Err(
                "catalog 'revoked'[].id is required; an entry without one cannot be matched to a capability"
                    .to_owned(),
            )
        }
    };

    let reason = match entry.get("reason") {
        None | Some(serde_json::Value::Null) => String::new(),
        Some(serde_json::Value::String(reason)) => reason.clone(),
        Some(other) => {
            return Err(format!(
                "catalog 'revoked'[].reason must be a string, found {}",
                json_kind(other)
            ))
        }
    };

    Ok(RevokedEntry { id, reason })
}

/// Human-readable JSON type, for messages a maintainer can act on.
fn json_kind(value: &serde_json::Value) -> &'static str {
    match value {
        serde_json::Value::Null => "null",
        serde_json::Value::Bool(_) => "a boolean",
        serde_json::Value::Number(_) => "a number",
        serde_json::Value::String(_) => "a string",
        serde_json::Value::Array(_) => "an array",
        serde_json::Value::Object(_) => "an object",
    }
}

/// Serde hook for [`CommunityCatalog::revoked`].
///
/// Reads the raw value first so *absent* stays distinguishable from
/// *malformed*: `#[serde(default)]` covers the missing-key case and a
/// `null` collapses to `None` here, while a value of the wrong type is
/// handed to [`parse_revocations`] and reported against the field it
/// broke rather than against the catalogue as a whole.
fn deserialize_revocations<'de, D>(deserializer: D) -> Result<Vec<RevokedEntry>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let raw = Option::<serde_json::Value>::deserialize(deserializer)?;
    parse_revocations(raw.as_ref()).map_err(serde::de::Error::custom)
}

fn pin_pinned_public_key(dir: &Path, key: &VerifyingKey) -> Result<(), String> {
    std::fs::create_dir_all(dir)
        .map_err(|error| format!("could not create community cache dir: {error}"))?;
    let path = dir.join("pinned-public-key.bin");
    std::fs::write(&path, key.to_bytes())
        .map_err(|error| format!("could not persist pinned public key: {error}"))?;
    Ok(())
}

fn verify_signature(payload: &[u8], signature_b64: &str, key: &VerifyingKey) -> Result<(), String> {
    let signature_bytes = BASE64
        .decode(signature_b64.trim())
        .map_err(|error| format!("signature is not valid base64: {error}"))?;
    if signature_bytes.len() != 64 {
        return Err(format!(
            "signature must be 64 bytes (Ed25519), got {}",
            signature_bytes.len()
        ));
    }
    let signature_array: [u8; 64] = signature_bytes
        .as_slice()
        .try_into()
        .map_err(|error: std::array::TryFromSliceError| error.to_string())?;
    let signature = Signature::from_bytes(&signature_array);
    // Normalize the payload before verifying: strip a leading UTF-8 BOM and
    // fold CRLF line endings down to LF. Ed25519 is byte-exact, so any
    // difference between the bytes the maintainer signed and the bytes
    // served by the CDN (BOM added by a `Set-Content -Encoding utf8`,
    // CRLF inserted by a Windows clone) would otherwise fail verification
    // for a perfectly valid signature.
    let normalized = normalize_payload_for_verify(payload);
    key.verify(&normalized, &signature)
        .map_err(|error| format!("signature verification failed: {error}"))
}

/// Make the payload match the canonical form maintainers sign:
///
/// * no leading UTF-8 BOM (`EF BB BF`)
/// * line endings folded to LF (`0A`)
///
/// Anything else (UTF-16 BOMs, trailing bytes, etc.) is left alone —
/// the signature will still fail loudly in those cases, which is what
/// we want for any unexpected CDN transformation.
fn normalize_payload_for_verify(payload: &[u8]) -> Vec<u8> {
    let mut start = 0usize;
    if payload.len() >= 3 && payload[..3] == [0xEF, 0xBB, 0xBF] {
        start = 3;
    }
    let mut out = Vec::with_capacity(payload.len() - start);
    let mut i = start;
    while i < payload.len() {
        let b = payload[i];
        if b == b'\r' && i + 1 < payload.len() && payload[i + 1] == b'\n' {
            out.push(b'\n');
            i += 2;
        } else {
            out.push(b);
            i += 1;
        }
    }
    out
}

/// Fetch the community catalog, honouring the cached TTL unless
/// `force_refresh` is set.
pub async fn fetch(force_refresh: bool, ttl_override: Option<u64>) -> CommunityFetchResult {
    let mut ttl_seconds = ttl_override
        .unwrap_or(DEFAULT_TTL_SECONDS)
        .clamp(MIN_TTL_SECONDS, MAX_TTL_SECONDS);
    let dir = match community_dir() {
        Some(dir) => dir,
        None => return empty_result(ttl_seconds, "LOCALAPPDATA not set".to_owned()),
    };

    if !force_refresh {
        // The cached catalogue is only served if its bytes still verify
        // against the keyring. A tampered cache is treated as no cache at
        // all: falling through to the network is the safe response, and
        // it is the only one that cannot be defeated by writing files.
        match read_verified_cached_catalog(&dir) {
            Ok((catalog, meta, key)) => {
                if meta.ttl_seconds != 0 {
                    ttl_seconds = meta.ttl_seconds;
                }
                let age = now_unix().saturating_sub(meta.cached_at);
                if age < ttl_seconds {
                    return CommunityFetchResult {
                        catalog,
                        cached: true,
                        cached_at: meta.cached_at,
                        ttl_seconds,
                        signature_verified: true,
                        bootstrap_public_key_fingerprint: fingerprint(&key),
                        last_error: None,
                    };
                }
            }
            Err(error) => {
                eprintln!("moddin: cached community catalog rejected: {error}");
            }
        }
    }

    let key = match ensure_bootstrap_key_material(&dir) {
        Ok(key) => key,
        Err(error) => return empty_result(ttl_seconds, error),
    };

    let client = match reqwest::Client::builder()
        .user_agent("Moddin-Desktop/0.1 (+https://github.com/petonexus/moddin-desktop)")
        .build()
    {
        Ok(client) => client,
        Err(error) => {
            return empty_result(ttl_seconds, format!("could not build HTTP client: {error}"))
        }
    };

    let catalog_response = match client.get(CATALOG_URL).send().await {
        Ok(response) => response,
        Err(error) => {
            return fallback_to_cache(&dir, ttl_seconds, format!("catalog GET failed: {error}"))
                .await
        }
    };
    if !catalog_response.status().is_success() {
        return fallback_to_cache(
            &dir,
            ttl_seconds,
            format!("catalog GET returned HTTP {}", catalog_response.status()),
        )
        .await;
    }
    let catalog_bytes = match catalog_response.bytes().await {
        Ok(bytes) => bytes,
        Err(error) => {
            return fallback_to_cache(
                &dir,
                ttl_seconds,
                format!("could not read catalog bytes: {error}"),
            )
            .await
        }
    };

    let signature_response = match client.get(CATALOG_SIG_URL).send().await {
        Ok(response) => response,
        Err(error) => {
            return fallback_to_cache(
                &dir,
                ttl_seconds,
                format!("catalog signature GET failed: {error}"),
            )
            .await
        }
    };
    let signature_text = match signature_response.text().await {
        Ok(text) => text,
        Err(error) => {
            return fallback_to_cache(
                &dir,
                ttl_seconds,
                format!("catalog signature read failed: {error}"),
            )
            .await
        }
    };

    if let Err(error) = verify_signature(&catalog_bytes, &signature_text, &key) {
        return fallback_to_cache(&dir, ttl_seconds, error).await;
    }

    // The signature is checked before the bytes are parsed, and a
    // parse failure here is a refusal rather than a cache write: a
    // catalogue whose `revoked` value is malformed must never become
    // the cached answer, and the raw bytes stay untouched for the next
    // read so the reason survives.
    let catalog: CommunityCatalog = match serde_json::from_slice(&catalog_bytes) {
        Ok(catalog) => catalog,
        Err(error) => return empty_result(ttl_seconds, format!("catalog JSON malformed: {error}")),
    };

    let fingerprint_value = fingerprint(&key);
    if let Err(error) = pin_pinned_public_key(&dir, &key) {
        return empty_result(
            ttl_seconds,
            format!("could not persist pinned key: {error}"),
        );
    }
    let metadata = CacheMetadata {
        cached_at: now_unix(),
        ttl_seconds,
        signature_verified: true,
        bootstrap_fingerprint: fingerprint_value.clone(),
    };
    if let Err(error) = write_cache(&dir, &catalog_bytes, &signature_text, &metadata) {
        return empty_result(ttl_seconds, format!("could not write cache: {error}"));
    }

    CommunityFetchResult {
        catalog,
        cached: false,
        cached_at: metadata.cached_at,
        ttl_seconds,
        signature_verified: true,
        bootstrap_public_key_fingerprint: fingerprint_value,
        last_error: None,
    }
}

async fn fallback_to_cache(dir: &Path, ttl_seconds: u64, error: String) -> CommunityFetchResult {
    match read_verified_cached_catalog(dir) {
        Ok((catalog, meta, key)) => CommunityFetchResult {
            catalog,
            cached: true,
            cached_at: meta.cached_at,
            ttl_seconds,
            signature_verified: true,
            bootstrap_public_key_fingerprint: fingerprint(&key),
            last_error: Some(error),
        },
        // A cache that does not verify is not a cache. Reporting it as
        // one with `signatureVerified` copied from its own metadata file
        // is how a writable `%LOCALAPPDATA%` became a signing oracle.
        Err(cache_error) => empty_result(
            ttl_seconds,
            format!("{error}; cached catalog rejected: {cache_error}"),
        ),
    }
}

fn empty_result(ttl_seconds: u64, error: String) -> CommunityFetchResult {
    CommunityFetchResult {
        catalog: CommunityCatalog {
            version: 1,
            generated_at: String::new(),
            generator: String::new(),
            capabilities: Vec::new(),
            revoked: Vec::new(),
        },
        cached: false,
        cached_at: 0,
        ttl_seconds,
        signature_verified: false,
        bootstrap_public_key_fingerprint: String::new(),
        last_error: Some(error),
    }
}

pub fn set_ttl(ttl_seconds: u64) -> u64 {
    ttl_seconds.clamp(MIN_TTL_SECONDS, MAX_TTL_SECONDS)
}

/// Resolve the catalog entry a community install is allowed to act on.
///
/// This is the single gate `community_capability_install` goes through,
/// and it is deliberately the same gate the UI went through: the cached
/// bytes are re-verified against the keyring *now*, and the capability
/// must be absent from the catalogue's `revoked` list.
///
/// # Why the signature comes first now
///
/// This used to consult the kill switch *before* the signature, on the
/// argument that an unauthenticated list could only add refusals and
/// never remove one. That argument is gone with the second fetch: the
/// revocations are inside the signed bytes, so there is nothing left to
/// read before the signature — reading them first would mean trusting
/// unsigned bytes, which is the defect the inlining removed.
///
/// What replaces the monotonicity is stronger. An attacker who wants to
/// drop a revocation now has to edit `catalog.json`, which invalidates
/// the signature and refuses **every** community install rather than
/// quietly restoring one. A tampered list can no longer remove a
/// refusal, because there is no untampered-of list to remove it from.
///
/// # Fail-closed inventory
///
/// Refused: no cache at all, missing or invalid `catalog.sig`, a
/// signature that verifies under no key in the ring, `catalog.json`
/// that is not valid JSON, and a `revoked` value that is not an array
/// of `{id, reason}` objects. A signed catalogue with no `revoked` key
/// is *not* a failure — it is the maintainer stating that nothing is
/// revoked; see [`parse_revocations`].
///
/// # Restores
///
/// Revocation governs installs, not restores. A snapshot restore
/// ([`crate::transaction::restore_record`]) copies files back from the
/// transaction's own backups and never reads the catalogue, so a user
/// who installed a capability before it was revoked can still undo or
/// restore it. Nothing in this module should be added to that path:
/// refusing to restore would strand a user with files they cannot get
/// out of their game folder.
pub fn verified_entry_for_install(capability_id: &str) -> Result<CommunityCatalogEntry, String> {
    verified_entry_with_keys(capability_id, TRUSTED_PUBLIC_KEYS_B64)
}

/// [`verified_entry_for_install`] against an explicit key list, for the
/// same reason [`verify_with_keys`] takes one: the build ships no
/// private key, so a test that wants to prove a revocation is
/// *enforced* has to be able to produce a catalogue the app accepts.
fn verified_entry_with_keys(
    capability_id: &str,
    keys: &[&str],
) -> Result<CommunityCatalogEntry, String> {
    let dir = community_dir().ok_or_else(|| {
        "LOCALAPPDATA not set, so the community catalog cannot be verified.".to_owned()
    })?;

    // One read, one verification, one list. The kill switch and the
    // capability entry cannot come from different documents, so they
    // cannot disagree about whether this capability is live.
    let (catalog, _meta, _key) = read_verified_cached_catalog_with_keys(&dir, keys).map_err(|error| {
        format!("Community catalog could not be verified: {error}. Fetch it again before installing.")
    })?;

    if let Some(entry) = catalog
        .revoked
        .iter()
        .find(|revoked| revoked.id == capability_id)
    {
        let reason = if entry.reason.trim().is_empty() {
            "no reason published".to_owned()
        } else {
            entry.reason.clone()
        };
        return Err(format!(
            "Community capability '{}' has been revoked by its maintainers: {reason}",
            capability_id
        ));
    }

    let entry = catalog
        .capabilities
        .iter()
        .find(|candidate| candidate.id == capability_id)
        .cloned()
        .ok_or_else(|| {
            format!(
                "Community catalog does not list a capability named '{}'.",
                capability_id
            )
        })?;
    if entry.download_url.is_none() {
        return Err(format!(
            "Community catalog entry '{}' has no downloadUrl.",
            capability_id
        ));
    }
    Ok(entry)
}

/// Download a single capability YAML from a community download URL,
/// and the sibling `SIGNED-BY` when present. Returns `(yaml_text,
/// signed_by_text_or_none)`. Network errors are surfaced as `Err(String)`
/// verbatim — the caller decides whether to fail-closed or fall back.
///
/// `host_allowlist` replaces [`CAPABILITY_YAML_HOST_ALLOWLIST`] only when
/// a caller *explicitly* passes one; there is no implicit widening, so
/// an unexpected host is a refusal rather than a silent fetch.
pub async fn fetch_capability_yaml(
    download_url: &str,
    host_allowlist: Option<&[String]>,
) -> Result<(String, Option<String>), String> {
    let allowed: Vec<String> = match host_allowlist {
        Some(hosts) => hosts
            .iter()
            .map(|host| host.trim().to_ascii_lowercase())
            .filter(|host| !host.is_empty())
            .collect(),
        None => CAPABILITY_YAML_HOST_ALLOWLIST
            .iter()
            .map(|host| (*host).to_owned())
            .collect(),
    };
    let parsed = validate_capability_yaml_url(download_url, &allowed)?;

    let client = reqwest::Client::builder()
        .user_agent("Moddin-Desktop/0.1 (+https://github.com/petonexus/moddin-desktop)")
        .build()
        .map_err(|error| format!("community: could not build HTTP client: {error}"))?;

    let yaml_bytes = client
        .get(parsed)
        .send()
        .await
        .map_err(|error| format!("community: YAML GET failed: {error}"))?
        .error_for_status()
        .map_err(|error| format!("community: YAML GET returned an error: {error}"))?
        .bytes()
        .await
        .map_err(|error| format!("community: YAML read failed: {error}"))?;
    // Preserve the exact signed bytes, including BOM and line endings.
    let yaml = String::from_utf8(yaml_bytes.to_vec())
        .map_err(|error| format!("community: YAML is not UTF-8: {error}"))?;

    // The `SIGNED-BY` sibling lives in the same directory, so the base
    // URL already passed the allow-list; it inherits the decision.
    let signed_by_url = sibling_url(download_url, "SIGNED-BY");
    let signed_by = match signed_by_url {
        Some(url) => match client.get(&url).send().await {
            Ok(response) if response.status().is_success() => response
                .text()
                .await
                .ok()
                .filter(|text| !text.trim().is_empty()),
            _ => None,
        },
        None => None,
    };

    Ok((yaml, signed_by))
}

/// HTTPS + no credentials + host on the allow-list. Split out from the
/// fetch so the policy is unit-testable without a network round-trip.
fn validate_capability_yaml_url(
    download_url: &str,
    allowlist: &[String],
) -> Result<reqwest::Url, String> {
    let url = reqwest::Url::parse(download_url.trim())
        .map_err(|error| format!("community: capability URL is not a valid URL: {error}"))?;
    if url.scheme() != "https" {
        return Err("community: capability URL must use HTTPS.".to_owned());
    }
    if !url.username().is_empty() || url.password().is_some() {
        return Err("community: capability URL must not carry credentials.".to_owned());
    }
    let host = url
        .host_str()
        .ok_or_else(|| "community: capability URL has no host.".to_owned())?
        .to_ascii_lowercase();
    if !allowlist.contains(&host) {
        return Err(format!(
            "community: host '{host}' is not in the allow-list ({}).",
            allowlist.join(", ")
        ));
    }
    Ok(url)
}

fn sibling_url(download_url: &str, sibling: &str) -> Option<String> {
    let last_slash = download_url.rfind('/')?;
    Some(format!("{}{}", &download_url[..=last_slash], sibling))
}

// === Tauri command surface =====================================================

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunityFetchRequest {
    #[serde(default)]
    pub force_refresh: bool,
    #[serde(default)]
    pub ttl_seconds: Option<u64>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunitySetTtlRequest {
    pub ttl_seconds: u64,
}

#[tauri::command]
pub async fn community_catalog_fetch(request: CommunityFetchRequest) -> CommunityFetchResult {
    fetch(request.force_refresh, request.ttl_seconds).await
}

#[tauri::command]
pub async fn community_catalog_set_ttl(request: CommunitySetTtlRequest) -> Result<u64, String> {
    Ok(set_ttl(request.ttl_seconds))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ttl_clamp_floor_and_ceiling() {
        assert_eq!(set_ttl(0), MIN_TTL_SECONDS);
        assert_eq!(set_ttl(60), MIN_TTL_SECONDS);
        assert_eq!(set_ttl(24 * 60 * 60), 24 * 60 * 60);
        assert_eq!(set_ttl(365 * 24 * 60 * 60), MAX_TTL_SECONDS);
    }

    #[test]
    fn bootstrap_key_decodes_to_32_bytes() {
        let bytes = BASE64
            .decode(BOOTSTRAP_PUBLIC_KEY_B64)
            .expect("placeholder is valid base64");
        assert_eq!(bytes.len(), 32, "Ed25519 public keys are 32 bytes");
    }

    /// Every key the app ships in the trust list has to decode, or a
    /// rotation that ships a typo silently stops trusting a key.
    #[test]
    fn every_trusted_key_in_the_keyring_decodes() {
        for encoded in TRUSTED_PUBLIC_KEYS_B64 {
            let key = decode_public_key(encoded).unwrap_or_else(|error| {
                panic!("trust list entry {encoded} does not decode: {error}")
            });
            assert!(is_trusted(&key), "{encoded} is in the list but not trusted");
        }
    }

    #[test]
    fn the_anchor_is_itself_trusted() {
        let anchor = decode_public_key(BOOTSTRAP_PUBLIC_KEY_B64).expect("anchor decodes");
        assert!(
            is_trusted(&anchor),
            "the compiled anchor must be present in the trust list"
        );
    }

    /// The pin on disk used to be returned unverified. Anything able to
    /// write to %LOCALAPPDATA% could drop in its own 32 bytes and sign
    /// whatever it liked, and the app would call it verified.
    #[test]
    fn a_pin_that_is_not_in_the_trust_list_is_discarded_for_the_anchor() {
        let dir = std::env::temp_dir().join(format!(
            "moddin-community-pin-{}-{}",
            std::process::id(),
            now_unix()
        ));
        std::fs::create_dir_all(&dir).expect("temp community dir");

        // A well-formed Ed25519 point that is in nobody's keyring. The
        // decode is asserted rather than skipped: a test that quietly
        // no-ops when its key is malformed is worse than no test.
        let attacker = decode_public_key("3pTDeCH5FEXkAdT1GVcE6McbxoHqTzZ1CkjPGCPYE9I=")
            .expect("the test key is a valid Ed25519 point");
        assert!(!is_trusted(&attacker), "test key must not be trusted");
        std::fs::write(dir.join("pinned-public-key.bin"), attacker.to_bytes())
            .expect("write attacker pin");

        let resolved = ensure_bootstrap_key_material(&dir).expect("falls back to the anchor");
        let anchor = decode_public_key(BOOTSTRAP_PUBLIC_KEY_B64).expect("anchor decodes");
        assert_eq!(
            resolved.to_bytes(),
            anchor.to_bytes(),
            "an untrusted pin must never be the key the catalog is verified with"
        );
        assert!(
            is_trusted(&resolved),
            "whatever we resolve to is still a key we trust"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_corrupt_pin_is_discarded_for_the_anchor() {
        let dir = std::env::temp_dir().join(format!(
            "moddin-community-corrupt-pin-{}-{}",
            std::process::id(),
            now_unix()
        ));
        std::fs::create_dir_all(&dir).expect("temp community dir");
        std::fs::write(dir.join("pinned-public-key.bin"), b"too short").expect("write corrupt pin");

        let resolved = ensure_bootstrap_key_material(&dir).expect("falls back to the anchor");
        let anchor = decode_public_key(BOOTSTRAP_PUBLIC_KEY_B64).expect("anchor decodes");
        assert_eq!(resolved.to_bytes(), anchor.to_bytes());

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A pin that matches the anchor is kept, so the on-disk cache
    /// still does its job and does not churn on every call.
    #[test]
    fn a_pin_matching_the_anchor_is_accepted() {
        let dir = std::env::temp_dir().join(format!(
            "moddin-community-good-pin-{}-{}",
            std::process::id(),
            now_unix()
        ));
        std::fs::create_dir_all(&dir).expect("temp community dir");
        let anchor = decode_public_key(BOOTSTRAP_PUBLIC_KEY_B64).expect("anchor decodes");
        std::fs::write(dir.join("pinned-public-key.bin"), anchor.to_bytes())
            .expect("write anchor pin");

        let resolved = ensure_bootstrap_key_material(&dir).expect("anchor pin accepted");
        assert_eq!(resolved.to_bytes(), anchor.to_bytes());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn signature_rejects_invalid_base64() {
        let key =
            ensure_bootstrap_key_material(&std::env::temp_dir()).expect("bootstrap key material");
        let error = verify_signature(b"payload", "@@@not-base64@@@", &key)
            .expect_err("must reject malformed signature");
        assert!(error.contains("base64"));
    }

    #[test]
    fn signature_rejects_wrong_length() {
        let key =
            ensure_bootstrap_key_material(&std::env::temp_dir()).expect("bootstrap key material");
        let error = verify_signature(b"payload", &BASE64.encode([0u8; 32]), &key)
            .expect_err("must reject 32-byte signature");
        assert!(error.contains("64 bytes"));
    }

    #[test]
    fn normalize_strips_leading_utf8_bom() {
        let payload = b"\xEF\xBB\xBF{\"version\":1}";
        let normalized = normalize_payload_for_verify(payload);
        assert_eq!(normalized, b"{\"version\":1}");
    }

    #[test]
    fn normalize_keeps_bom_in_the_middle_alone() {
        // A BOM anywhere except the start must NOT be stripped — otherwise a
        // genuine BOM in the payload body would be silently mutated and the
        // signature would still fail. Defensive: only the leading BOM gets
        // normalized.
        let payload = b"{\"a\":\"\xEF\xBB\xBF\"}";
        let normalized = normalize_payload_for_verify(payload);
        assert_eq!(normalized, b"{\"a\":\"\xEF\xBB\xBF\"}");
    }

    #[test]
    fn normalize_folds_crlf_to_lf() {
        let payload = b"line1\r\nline2\r\nline3";
        let normalized = normalize_payload_for_verify(payload);
        assert_eq!(normalized, b"line1\nline2\nline3");
    }

    #[test]
    fn normalize_handles_trailing_cr_without_lf() {
        // A bare CR at the end of the file (no LF after) is unusual but valid;
        // the normalizer must not eat it.
        let payload = b"line1\nline2\r";
        let normalized = normalize_payload_for_verify(payload);
        assert_eq!(normalized, b"line1\nline2\r");
    }

    #[test]
    fn normalize_combined_bom_and_crlf() {
        let payload = b"\xEF\xBB\xBFline1\r\nline2\r\nline3";
        let normalized = normalize_payload_for_verify(payload);
        assert_eq!(normalized, b"line1\nline2\nline3");
    }

    #[test]
    fn signature_verifies_across_bom_and_crlf() {
        // Build a keypair, sign the canonical payload, then confirm that
        // wrapping the same payload in a leading BOM and CRLF still verifies.
        // This is the regression test for the catalog mismatch bug where
        // GitHub served the catalog with BOM + LF but the .sig was generated
        // over a different byte form.
        use ed25519_dalek::{Signer, SigningKey};
        let mut seed = [0u8; 32];
        for (i, byte) in seed.iter_mut().enumerate() {
            *byte = i as u8;
        }
        let signing_key = SigningKey::from_bytes(&seed);
        let verifying_key = signing_key.verifying_key();
        let canonical: &[u8] = b"line1\nline2\nline3\n";
        let signature: ed25519_dalek::Signature = signing_key.sign(canonical);
        let sig_b64 = BASE64.encode(signature.to_bytes());

        // The same logical content, but with a leading BOM and CRLF endings —
        // exactly the form a Windows clone of the repo + a `Set-Content
        // -Encoding utf8` upload would produce.
        let mut with_bom_and_crlf: Vec<u8> = vec![0xEF, 0xBB, 0xBF];
        for line in canonical.split(|byte| *byte == b'\n') {
            if line.is_empty() {
                // Trailing LF in the canonical becomes \r\n with the BOM wrapper
                // but no trailing CR after the final newline.
                continue;
            }
            with_bom_and_crlf.extend_from_slice(line);
            with_bom_and_crlf.extend_from_slice(b"\r\n");
        }

        // Sanity: normalization must collapse BOM + CRLF back to canonical.
        let normalized = normalize_payload_for_verify(&with_bom_and_crlf);
        assert_eq!(normalized, canonical, "test setup is wrong");

        verify_signature(&with_bom_and_crlf, &sig_b64, &verifying_key)
            .expect("normalized verification must accept the wrapped payload");
    }

    #[test]
    fn fingerprint_is_short_hex() {
        let key =
            ensure_bootstrap_key_material(&std::env::temp_dir()).expect("bootstrap key material");
        let value = fingerprint(&key);
        assert_eq!(value.len(), 16);
        assert!(value.chars().all(|character| character.is_ascii_hexdigit()));
    }

    #[test]
    fn sibling_url_strips_filename_only() {
        let url = "https://raw.githubusercontent.com/petonexus/moddin-community-capabilities/main/capabilities/community-fps-unlocker/capability.yaml";
        let sibling = sibling_url(url, "SIGNED-BY").expect("sibling");
        assert_eq!(
            sibling,
            "https://raw.githubusercontent.com/petonexus/moddin-community-capabilities/main/capabilities/community-fps-unlocker/SIGNED-BY"
        );
    }

    #[test]
    fn sibling_url_rejects_strings_without_a_slash() {
        assert!(sibling_url("not-a-url", "X").is_none());
        assert!(sibling_url("", "X").is_none());
    }

    // -----------------------------------------------------------------
    // Cached-catalogue re-verification (ROADMAP F-03)
    // -----------------------------------------------------------------

    /// A keypair that is well-formed but belongs to nobody in the
    /// keyring. Every test below signs with it, and each one asserts the
    /// signature really is a valid signature for the payload first — a
    /// "rejected" cache that was actually rejected because the fixture
    /// was broken would pass for the right reason while testing nothing.
    fn attacker_keypair() -> (ed25519_dalek::SigningKey, VerifyingKey) {
        use ed25519_dalek::SigningKey;
        let mut seed = [0u8; 32];
        for (index, byte) in seed.iter_mut().enumerate() {
            *byte = (index as u8).wrapping_add(0x40);
        }
        let signing_key = SigningKey::from_bytes(&seed);
        let verifying_key = signing_key.verifying_key();
        assert!(
            !is_trusted(&verifying_key),
            "the attacker key must not be in the trust list, or these tests prove nothing"
        );
        (signing_key, verifying_key)
    }

    /// A minimal, well-formed catalogue whose single entry points at
    /// `download_url`, with the `revoked` value spliced in verbatim so
    /// a test can hand the deserializer a shape the generator would
    /// never emit. `None` omits the key entirely.
    ///
    /// Returned as raw bytes, because that is what the cache stores and
    /// what the signature has to cover.
    fn catalog_json(download_url: &str, revoked: Option<&str>) -> Vec<u8> {
        let mut root = serde_json::Map::new();
        root.insert("version".to_owned(), serde_json::json!(1));
        root.insert(
            "generatedAt".to_owned(),
            serde_json::json!("2026-09-29T00:00:00Z"),
        );
        root.insert("generator".to_owned(), serde_json::json!("test"));
        root.insert(
            "capabilities".to_owned(),
            serde_json::json!([{
                "id": "community-fps-unlocker",
                "version": "1.0.0",
                "displayName": "FPS Unlocker",
                "category": "performance",
                "status": "available",
                "homepage": serde_json::Value::Null,
                "downloadUrl": download_url,
                "configSchema": serde_json::Value::Null,
                "safetyNotes": [],
                "signed": true,
            }]),
        );
        if let Some(revoked) = revoked {
            let parsed: serde_json::Value = serde_json::from_str(revoked)
                .unwrap_or_else(|error| panic!("the fixture's revoked value is not JSON: {error}"));
            root.insert("revoked".to_owned(), parsed);
        }
        serde_json::to_vec_pretty(&serde_json::Value::Object(root)).expect("fixture serialises")
    }

    /// The common case: a catalogue with an empty, well-formed kill
    /// switch.
    fn catalog_fixture(download_url: &str) -> Vec<u8> {
        catalog_json(download_url, Some("[]"))
    }

    const TRUSTED_DOWNLOAD_URL: &str =
        "https://raw.githubusercontent.com/petonexus/moddin-community-capabilities/main/capabilities/community-fps-unlocker/capability.yaml";
    const ATTACKER_DOWNLOAD_URL: &str =
        "https://raw.githubusercontent.com/attacker/moddin-evil/main/capability.yaml";

    /// Write a cache the way an attacker with write access to
    /// `%LOCALAPPDATA%` would: the payload they want, plus a *valid*
    /// signature — theirs — plus metadata claiming it was verified.
    fn write_tampered_cache(dir: &Path, payload: &[u8]) {
        let (signing_key, _) = attacker_keypair();
        write_cache_signed_by(dir, payload, &signing_key);
    }

    /// Write a cache that is signed with a key nobody in the shipped
    /// keyring trusts, after asserting the signature really is valid
    /// for those exact bytes. A tampered cache that was actually
    /// rejected because the *fixture* was broken would pass for the
    /// right reason while testing nothing.
    fn write_cache_signed_by(dir: &Path, payload: &[u8], signing_key: &ed25519_dalek::SigningKey) {
        use ed25519_dalek::Signer;
        let signature: ed25519_dalek::Signature = signing_key.sign(payload);
        let sig_b64 = BASE64.encode(signature.to_bytes());

        // Non-vacuity: the signature is genuinely valid for these bytes,
        // just not under a key the app trusts. Without this assert the
        // tests below would also pass if the fixture were corrupt.
        verify_signature(payload, &sig_b64, &signing_key.verifying_key())
            .expect("the fixture signature is valid for the fixture payload");

        std::fs::create_dir_all(dir).expect("temp community dir");
        std::fs::write(dir.join(CATALOG_CACHE_FILE), payload).expect("write catalog.json");
        std::fs::write(dir.join(CATALOG_SIG_CACHE_FILE), &sig_b64).expect("write catalog.sig");
        std::fs::write(
            dir.join(CATALOG_META_FILE),
            serde_json::to_vec_pretty(&CacheMetadata {
                cached_at: now_unix(),
                ttl_seconds: DEFAULT_TTL_SECONDS,
                signature_verified: true,
                bootstrap_fingerprint: "deadbeefdeadbeef".to_owned(),
            })
            .expect("meta serialises"),
        )
        .expect("write catalog.meta.json");
    }

    /// A signing key for a catalogue that *should* be accepted, plus
    /// its base64 public key — the one entry of the one-key trust list
    /// that accepts it.
    ///
    /// The build ships no private key, so the only way to test the
    /// accept path is to hand the verification a different keyring.
    /// Production callers pass [`TRUSTED_PUBLIC_KEYS_B64`]; nothing else
    /// can. The key is asserted *not* to be in the shipped keyring, so
    /// a test using it can never quietly be testing the refusal path.
    fn trusted_fixture_keypair() -> (ed25519_dalek::SigningKey, String) {
        use ed25519_dalek::SigningKey;
        let mut seed = [0u8; 32];
        for (index, byte) in seed.iter_mut().enumerate() {
            *byte = (index as u8)
                .wrapping_add(0xA7)
                .wrapping_mul(7)
                .wrapping_add(11);
        }
        let signing_key = SigningKey::from_bytes(&seed);
        let encoded = BASE64.encode(signing_key.verifying_key().to_bytes());
        assert!(
            !is_trusted(&signing_key.verifying_key()),
            "the accepting fixture key must not be in the shipped keyring"
        );
        (signing_key, encoded)
    }

    fn temp_community_root(label: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "moddin-community-{label}-{}-{}",
            std::process::id(),
            now_unix()
        ));
        let dir = root.join("Moddin").join("community-capabilities");
        std::fs::create_dir_all(&dir).expect("temp community dir");
        root
    }

    fn restore_local_app_data(previous: Option<std::ffi::OsString>) {
        match previous {
            Some(value) => std::env::set_var("LOCALAPPDATA", value),
            None => std::env::remove_var("LOCALAPPDATA"),
        }
    }

    /// Point `community_dir()` at a fresh temp directory for the
    /// duration of `body`, and clean it up afterwards. Takes the
    /// process-wide env lock because `LOCALAPPDATA` is process-global.
    fn with_temp_community_dir<T>(label: &str, body: impl FnOnce(&Path) -> T) -> T {
        let _guard = crate::test_support::env_lock();
        let root = temp_community_root(label);
        let dir = root.join("Moddin").join("community-capabilities");

        let previous = std::env::var_os("LOCALAPPDATA");
        std::env::set_var("LOCALAPPDATA", &root);
        let outcome = body(&dir);
        restore_local_app_data(previous);

        let _ = std::fs::remove_dir_all(&root);
        outcome
    }

    /// The regression this whole block exists for: a catalogue on disk
    /// that carries a valid-but-untrusted signature, plus metadata that
    /// insists it was verified, must not hand a `downloadUrl` to the
    /// install path.
    #[test]
    fn a_cached_catalog_that_does_not_verify_against_the_keyring_is_not_used() {
        with_temp_community_dir("unsigned-cache", |dir| {
            // An empty (but well-formed) kill switch, so this test
            // measures the signature gate and not the revocation gate.
            write_tampered_cache(dir, &catalog_fixture(ATTACKER_DOWNLOAD_URL));

            // Control: the plain read *does* accept the tampered cache,
            // and hands back the attacker's URL. If it stopped doing so
            // the test below would pass for the wrong reason.
            let (raw, meta) =
                read_cached_catalog(dir).expect("the unverified read accepts the tampered cache");
            assert_eq!(
                raw.capabilities[0].download_url.as_deref(),
                Some(ATTACKER_DOWNLOAD_URL)
            );
            assert!(meta.signature_verified, "fixture must claim to be verified");

            // The gate: signature check against the compiled keyring.
            let error = read_verified_cached_catalog(dir)
                .expect_err("an untrusted signature must not open the cache");
            assert!(
                error.contains("signature")
                    || error.contains("64 bytes")
                    || error.contains("base64"),
                "unexpected rejection reason: {error}"
            );

            // And the install path, which is what actually reads a URL.
            let error = verified_entry_for_install("community-fps-unlocker")
                .expect_err("install must not resolve an entry from an unverified cache");
            assert!(
                error.contains("could not be verified"),
                "unexpected install refusal: {error}"
            );
        });
    }

    /// A cache whose signature file was deleted is a cache miss, not a
    /// licence to fall back to the unsigned payload.
    #[test]
    fn a_cached_catalog_without_a_signature_file_is_not_used() {
        with_temp_community_dir("no-sig", |dir| {
            write_tampered_cache(dir, &catalog_fixture(ATTACKER_DOWNLOAD_URL));
            std::fs::remove_file(dir.join(CATALOG_SIG_CACHE_FILE)).expect("remove catalog.sig");

            assert!(
                read_cached_catalog(dir).is_some(),
                "control: the raw read still sees the payload"
            );
            let error = read_verified_cached_catalog(dir).expect_err("missing signature is a miss");
            assert!(
                error.contains("signature is missing"),
                "unexpected reason: {error}"
            );
        });
    }

    /// `write_cache` must store the bytes that were signed, not a
    /// re-serialisation of the parsed value — otherwise the cache stops
    /// verifying the first time the app is run.
    #[test]
    fn write_cache_preserves_the_signed_bytes_verbatim() {
        with_temp_community_dir("write-cache", |dir| {
            // Pretty-printed with a trailing newline and a CRLF in the
            // middle: neither survives a `to_vec_pretty` round-trip.
            let payload = b"{\r\n  \"version\": 1\r\n}\n";
            let meta = CacheMetadata {
                cached_at: 1,
                ttl_seconds: 2,
                signature_verified: true,
                bootstrap_fingerprint: "abcdabcdabcdabcd".to_owned(),
            };
            write_cache(dir, payload, "c2ln", &meta).expect("write cache");

            let on_disk = std::fs::read(dir.join(CATALOG_CACHE_FILE)).expect("read back");
            assert_eq!(
                on_disk, payload,
                "the cache must hold the exact bytes the maintainer signed"
            );
            assert_eq!(
                std::fs::read_to_string(dir.join(CATALOG_SIG_CACHE_FILE)).expect("sig"),
                "c2ln"
            );
        });
    }

    // -----------------------------------------------------------------
    // YAML host allow-list (ROADMAP F-03)
    // -----------------------------------------------------------------

    fn default_hosts() -> Vec<String> {
        CAPABILITY_YAML_HOST_ALLOWLIST
            .iter()
            .map(|host| (*host).to_owned())
            .collect()
    }

    #[test]
    fn capability_yaml_url_accepts_the_github_hosts_by_default() {
        for host in [
            "github.com",
            "objects.githubusercontent.com",
            "raw.githubusercontent.com",
        ] {
            let url = format!("https://{host}/petonexus/capabilities/x/capability.yaml");
            validate_capability_yaml_url(&url, &default_hosts())
                .unwrap_or_else(|error| panic!("{host} must be allowed: {error}"));
        }
    }

    #[test]
    fn capability_yaml_url_refuses_a_host_outside_the_allow_list() {
        for url in [
            "https://evil.example.com/capability.yaml",
            "https://raw.githubusercontent.com.evil.test/capability.yaml",
            "https://notraw.githubusercontent.com/capability.yaml",
            "https://192.0.2.10/capability.yaml",
        ] {
            let error = validate_capability_yaml_url(url, &default_hosts())
                .expect_err("a host outside the allow-list must be refused");
            assert!(
                error.contains("not in the allow-list"),
                "{url} was refused for the wrong reason: {error}"
            );
        }
    }

    #[test]
    fn capability_yaml_url_refuses_plaintext_credentials_and_userinfo() {
        assert!(validate_capability_yaml_url(
            "http://raw.githubusercontent.com/a/b.yaml",
            &default_hosts()
        )
        .expect_err("plain HTTP must be refused")
        .contains("HTTPS"));
        assert!(validate_capability_yaml_url(
            "https://user:pass@raw.githubusercontent.com/a/b.yaml",
            &default_hosts()
        )
        .expect_err("embedded credentials must be refused")
        .contains("credentials"));
    }

    /// The allow-list is a closed default. It only opens when a caller
    /// explicitly passes a replacement — there is no implicit widening.
    #[test]
    fn capability_yaml_url_honours_an_explicit_allow_list() {
        let declared = vec!["caps.internal.test".to_owned()];
        validate_capability_yaml_url(
            "https://caps.internal.test/community/x/capability.yaml",
            &declared,
        )
        .expect("a declared host is allowed");
        let error =
            validate_capability_yaml_url("https://raw.githubusercontent.com/a/b.yaml", &declared)
                .expect_err("an explicit list replaces the default rather than adding to it");
        assert!(error.contains("not in the allow-list"), "{error}");
    }

    // -----------------------------------------------------------------
    // Capability-level revocation, inside the signed catalogue
    // (ROADMAP F-03)
    // -----------------------------------------------------------------

    // --- the shape the generator emits -------------------------------

    #[test]
    fn revocations_parse_the_published_shape() {
        let list = parse_revocations(Some(
            &serde_json::from_str::<serde_json::Value>(
                r#"[ { "id": "bad-actor", "reason": "ships a dropper" } ]"#,
            )
            .expect("fixture is JSON"),
        ))
        .expect("published shape parses");
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].id, "bad-actor");
        assert_eq!(list[0].reason, "ships a dropper");
    }

    #[test]
    fn an_empty_revocation_list_is_valid_and_revokes_nothing() {
        let empty = serde_json::from_str::<serde_json::Value>("[]").expect("fixture is JSON");
        assert!(parse_revocations(Some(&empty))
            .expect("empty list is valid")
            .is_empty());
    }

    /// A `reason` is optional. A revocation without one still revokes —
    /// the app substitutes a placeholder rather than reading the missing
    /// field as "not really revoked".
    #[test]
    fn a_revocation_without_a_reason_still_carries_an_id() {
        let list = parse_revocations(Some(
            &serde_json::from_str::<serde_json::Value>(r#"[ { "id": "bad-actor" } ]"#)
                .expect("fixture is JSON"),
        ))
        .expect("a reason is optional");
        assert_eq!(list[0].id, "bad-actor");
        assert!(list[0].reason.is_empty());
    }

    /// Ids are trimmed rather than compared byte for byte. A stray
    /// space in the maintainer's file must still revoke the capability
    /// instead of quietly missing it.
    #[test]
    fn a_revocation_id_is_trimmed() {
        let list = parse_revocations(Some(
            &serde_json::from_str::<serde_json::Value>(r#"[ { "id": "  bad-actor  " } ]"#)
                .expect("fixture is JSON"),
        ))
        .expect("a padded id is usable");
        assert_eq!(list[0].id, "bad-actor");
    }

    // --- the absent case, decided explicitly -------------------------

    /// The decision, in a test that says so: **an absent `revoked` key
    /// in a validly signed catalogue is the maintainer stating that
    /// nothing is revoked, not a failure.**
    ///
    /// Requiring the key would buy nothing. An attacker able to strip
    /// it could equally rewrite the whole catalogue — and then the
    /// signature check refuses every community install — so the key's
    /// absence adds no protection over the signature, while treating it
    /// as a failure would brick installs against any catalogue
    /// generated before the field existed.
    #[test]
    fn an_absent_revoked_field_is_a_statement_that_nothing_is_revoked() {
        let catalog: CommunityCatalog =
            serde_json::from_slice(&catalog_json(TRUSTED_DOWNLOAD_URL, None))
                .expect("a signed catalogue with no revoked key is readable");
        assert!(
            catalog.revoked.is_empty(),
            "an absent key must read as 'nothing is revoked', not as an error"
        );
    }

    /// An explicit `null` is the same statement as an absent key, and
    /// reads the same way.
    #[test]
    fn a_null_revoked_field_is_treated_like_an_absent_one() {
        let catalog: CommunityCatalog =
            serde_json::from_slice(&catalog_json(TRUSTED_DOWNLOAD_URL, Some("null")))
                .expect("a null revoked value is a statement, not a break");
        assert!(catalog.revoked.is_empty());
    }

    // --- the malformed case, which is the opposite ------------------

    /// A `revoked` value of the wrong shape is a broken file, not a
    /// statement, and it fails closed. Each of these would otherwise
    /// be read as "nothing is revoked" by a lenient parser.
    #[test]
    fn a_malformed_revoked_value_is_refused() {
        for (label, raw) in [
            ("an object", r#"{ "id": "bad-actor" }"#),
            ("a string", r#""bad-actor""#),
            ("a number", "42"),
            ("a boolean", "true"),
        ] {
            let value: serde_json::Value = serde_json::from_str(raw).expect("fixture is JSON");
            let error = parse_revocations(Some(&value))
                .expect_err("a value that is not an array must not parse");
            assert!(
                error.contains("must be an array"),
                "{label}: unexpected reason: {error}"
            );
        }
    }

    /// A malformed *entry* is never dropped on the floor. Guessing which
    /// capability an id-less revocation meant is exactly the "bounded
    /// but wrong" reading this module exists to avoid, so the whole
    /// catalogue is refused.
    #[test]
    fn a_malformed_revocation_entry_is_refused() {
        for (label, raw, needle) in [
            (
                "no id",
                r#"[ { "reason": "which one?" } ]"#,
                "id is required",
            ),
            ("empty id", r#"[ { "id": "" } ]"#, "non-empty string"),
            ("blank id", r#"[ { "id": "   " } ]"#, "non-empty string"),
            ("id is a number", r#"[ { "id": 7 } ]"#, "non-empty string"),
            (
                "entry is a string",
                r#"[ "bad-actor" ]"#,
                "must be an object",
            ),
            (
                "reason is a number",
                r#"[ { "id": "bad-actor", "reason": 3 } ]"#,
                "reason must be a string",
            ),
        ] {
            let value: serde_json::Value = serde_json::from_str(raw).expect("fixture is JSON");
            let error = parse_revocations(Some(&value))
                .expect_err("a malformed entry must not be silently accepted");
            assert!(
                error.contains(needle),
                "{label}: unexpected reason: {error}"
            );
        }
    }

    // --- enforcement, on a catalogue the app actually accepts --------

    /// The headline behaviour: a capability the maintainers revoked
    /// cannot be installed, whatever else the catalogue says. Signed
    /// with a key the test keyring trusts, so this is the *accept*
    /// path with the kill switch closed — not a refusal for some other
    /// reason.
    #[test]
    fn a_revocation_in_a_validly_signed_catalog_blocks_the_install() {
        with_temp_community_dir("revoked", |dir| {
            let (signing_key, key_b64) = trusted_fixture_keypair();
            let keys = [key_b64.as_str()];
            let payload = catalog_json(
                TRUSTED_DOWNLOAD_URL,
                Some(r#"[ { "id": "community-fps-unlocker", "reason": "ships a keylogger" } ]"#),
            );
            write_cache_signed_by(dir, &payload, &signing_key);

            // Control: the very same cache resolves when nothing is
            // revoked. Without this the refusal below could be passing
            // for the wrong reason.
            let (catalog, _meta, _key) = read_verified_cached_catalog_with_keys(dir, &keys)
                .expect("the fixture catalogue is accepted by the test keyring");
            assert_eq!(catalog.revoked.len(), 1);

            let error = verified_entry_with_keys("community-fps-unlocker", &keys)
                .expect_err("a revoked capability must be refused");
            assert!(
                error.contains("has been revoked"),
                "unexpected refusal: {error}"
            );
            assert!(
                error.contains("ships a keylogger"),
                "the reason must reach the UI: {error}"
            );
        });
    }

    /// The control above, stated on its own so the accept path is
    /// covered even if the revocation test changes.
    #[test]
    fn a_live_capability_in_a_validly_signed_catalog_installs() {
        with_temp_community_dir("live", |dir| {
            let (signing_key, key_b64) = trusted_fixture_keypair();
            let keys = [key_b64.as_str()];
            write_cache_signed_by(dir, &catalog_fixture(TRUSTED_DOWNLOAD_URL), &signing_key);

            let entry = verified_entry_with_keys("community-fps-unlocker", &keys)
                .expect("a live capability in a signed catalogue installs");
            assert_eq!(entry.download_url.as_deref(), Some(TRUSTED_DOWNLOAD_URL));
        });
    }

    /// The signed catalogue carries both the capability and the
    /// revocation of it. The revocation has to win, or "revoked" would
    /// depend on which half of the document the app happened to read.
    #[test]
    fn a_revocation_beats_the_capability_entry_that_lists_the_same_id() {
        with_temp_community_dir("revoked-but-listed", |dir| {
            let (signing_key, key_b64) = trusted_fixture_keypair();
            let keys = [key_b64.as_str()];
            let payload = catalog_json(
                TRUSTED_DOWNLOAD_URL,
                Some(r#"[ { "id": "community-fps-unlocker", "reason": "withdrawn" } ]"#),
            );
            write_cache_signed_by(dir, &payload, &signing_key);

            let catalog: CommunityCatalog =
                serde_json::from_slice(&payload).expect("fixture parses");
            assert_eq!(
                catalog.capabilities.len(),
                1,
                "the capability is still listed"
            );
            let error = verified_entry_with_keys("community-fps-unlocker", &keys)
                .expect_err("being listed in the same document does not un-revoke");
            assert!(
                error.contains("has been revoked"),
                "unexpected refusal: {error}"
            );
        });
    }

    /// A revocation with no reason published is still a revocation, and
    /// the message must not read as an empty sentence.
    #[test]
    fn a_revocation_with_no_reason_is_still_refused() {
        with_temp_community_dir("revoked-noreason", |dir| {
            let (signing_key, key_b64) = trusted_fixture_keypair();
            let keys = [key_b64.as_str()];
            let payload = catalog_json(
                TRUSTED_DOWNLOAD_URL,
                Some(r#"[ { "id": "community-fps-unlocker" } ]"#),
            );
            write_cache_signed_by(dir, &payload, &signing_key);

            let error = verified_entry_with_keys("community-fps-unlocker", &keys)
                .expect_err("a revocation with no reason must still be refused");
            assert!(
                error.contains("has been revoked"),
                "unexpected refusal: {error}"
            );
            assert!(
                error.contains("no reason published"),
                "an empty reason must not produce an empty sentence: {error}"
            );
        });
    }

    /// Revoking `a` must not revoke `b`.
    #[test]
    fn a_revocation_only_matches_its_own_id() {
        with_temp_community_dir("revoked-other", |dir| {
            let (signing_key, key_b64) = trusted_fixture_keypair();
            let keys = [key_b64.as_str()];
            let payload = catalog_json(
                TRUSTED_DOWNLOAD_URL,
                Some(r#"[ { "id": "something-else" } ]"#),
            );
            write_cache_signed_by(dir, &payload, &signing_key);

            verified_entry_with_keys("community-fps-unlocker", &keys)
                .expect("a different id must not be treated as revoked");
        });
    }

    // --- the signature gate, which now comes first ------------------

    /// Non-vacuity for the attacker fixture, on its own: the signature
    /// it carries really does verify for the bytes on disk. Every
    /// refusal below would still "pass" if this were false.
    #[test]
    fn the_attacker_fixture_signature_is_genuinely_valid_for_its_payload() {
        with_temp_community_dir("attacker-non-vacuity", |dir| {
            let (signing_key, verifying_key) = attacker_keypair();
            let payload = catalog_fixture(ATTACKER_DOWNLOAD_URL);
            write_cache_signed_by(dir, &payload, &signing_key);

            let signature = BASE64.encode({
                use ed25519_dalek::Signer;
                signing_key.sign(&payload).to_bytes()
            });
            verify_signature(&payload, &signature, &verifying_key)
                .expect("the attacker's signature is valid for the attacker's payload");
            assert!(
                verify_with_keys(&payload, &signature, TRUSTED_PUBLIC_KEYS_B64).is_err(),
                "and it is still refused by the shipped keyring"
            );
        });
    }

    /// A catalogue that does not verify is refused outright — including
    /// when it carries a revocation, and including when the revocation
    /// is the attacker's own. This is the replacement for the old
    /// "check the kill switch first" ordering: the revocations are only
    /// meaningful because they are inside the signed bytes, so an
    /// unverifiable document yields no revocations *and* no capability
    /// list. There is nothing to be gained by pretending otherwise.
    #[test]
    fn a_catalog_whose_signature_does_not_verify_is_refused_revoked_or_not() {
        for (label, revoked) in [
            ("nothing revoked", "[]"),
            (
                "attacker drops a real revocation",
                r#"[ { "id": "community-fps-unlocker", "reason": "withdrawn" } ]"#,
            ),
            ("attacker un-revokes", r#"[ { "id": "something-else" } ]"#),
        ] {
            with_temp_community_dir("unsigned-revoked", |dir| {
                write_tampered_cache(dir, &catalog_json(ATTACKER_DOWNLOAD_URL, Some(revoked)));

                let error = verified_entry_for_install("community-fps-unlocker")
                    .expect_err("an unverified catalogue must never produce an install");
                assert!(
                    error.contains("could not be verified"),
                    "{label}: unexpected refusal: {error}"
                );
                assert!(
                    !error.contains("has been revoked"),
                    "{label}: the kill switch must not be read out of an unverified document: {error}"
                );
            });
        }
    }

    /// The malformed case, all the way through the install gate with a
    /// signature that *does* verify. A valid signature does not make a
    /// broken value trustworthy, and it must not turn a typo into "no
    /// revocations".
    #[test]
    fn a_malformed_revoked_value_in_a_validly_signed_catalog_fails_closed() {
        for (label, raw) in [
            ("not an array", r#"{ "id": "bad-actor" }"#),
            ("entry without an id", r#"[ { "reason": "which one?" } ]"#),
            ("entry is a string", r#"[ "bad-actor" ]"#),
        ] {
            with_temp_community_dir("signed-but-malformed", |dir| {
                let (signing_key, key_b64) = trusted_fixture_keypair();
                let keys = [key_b64.as_str()];
                let payload = catalog_json(TRUSTED_DOWNLOAD_URL, Some(raw));
                write_cache_signed_by(dir, &payload, &signing_key);

                let error = verified_entry_with_keys("community-fps-unlocker", &keys)
                    .expect_err("a broken kill switch must not read as an empty one");
                assert!(
                    error.contains("malformed") && error.contains("revoked"),
                    "{label}: unexpected refusal: {error}"
                );
            });
        }
    }

    // --- the shape the frontend reads -------------------------------

    /// The panel reads `catalog.revoked`; this is the wire contract
    /// for it. `revocationsVerified` is gone on purpose — the list
    /// arrives inside the signed bytes, so its trustworthiness is not a
    /// separate fact to report.
    #[test]
    fn the_fetch_result_carries_the_revocation_list_on_the_catalog() {
        let result = CommunityFetchResult {
            catalog: CommunityCatalog {
                version: 1,
                generated_at: "2026-09-29T00:00:00Z".to_owned(),
                generator: "test".to_owned(),
                capabilities: Vec::new(),
                revoked: vec![RevokedEntry {
                    id: "bad-actor".to_owned(),
                    reason: "ships a dropper".to_owned(),
                }],
            },
            cached: true,
            cached_at: 1,
            ttl_seconds: 2,
            signature_verified: true,
            bootstrap_public_key_fingerprint: "0123456789abcdef".to_owned(),
            last_error: None,
        };

        let json = serde_json::to_value(&result).expect("the result serialises");
        assert_eq!(json["catalog"]["revoked"][0]["id"], "bad-actor");
        assert_eq!(json["catalog"]["revoked"][0]["reason"], "ships a dropper");
        assert!(
            json.get("revocationsVerified").is_none(),
            "a flag that can only ever be true is not a fact worth sending"
        );
        assert!(json.get("revoked").is_none(), "one list, not two copies");
    }
}
